GET http://localhost:3001/api/records
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZnczIyMDAyIiwiaWQiOiI2NGI5MDYwMDljZDMwNjIwMDhkOTAxZjYiLCJpYXQiOjE2OTIyODgwNjMsImV4cCI6MTY5MjI5MTY2M30._AOwRNJtZE41eRIYgT5hBzlFRSMd-eeTbVPDtXFY40U
###
GET http://localhost:3000/api/records/64933ab572abcf94f8e852ec
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZnczIyMDAyIiwiaWQiOiI2NGI5MDYwMDljZDMwNjIwMDhkOTAxZjYiLCJpYXQiOjE2OTAwMzc0MTAsImV4cCI6MTY5MDA0MTAxMH0.XK8flz7l04sKBWQ4mwCLk2f8LOB3E0MqvKhBMsrxILg
###
DELETE http://localhost:3000/api/records/64bbeecc7f4d6df4a34b4b68
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZnczIyMDAyIiwiaWQiOiI2NGI5MDYwMDljZDMwNjIwMDhkOTAxZjYiLCJpYXQiOjE2OTAwMzc0MTAsImV4cCI6MTY5MDA0MTAxMH0.XK8flz7l04sKBWQ4mwCLk2f8LOB3E0MqvKhBMsrxILg
###
POST http://localhost:3000/api/records
Content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZnczIyMDAyIiwiaWQiOiI2NGI5MDYwMDljZDMwNjIwMDhkOTAxZjYiLCJpYXQiOjE2OTAwMzc0MTAsImV4cCI6MTY5MDA0MTAxMH0.XK8flz7l04sKBWQ4mwCLk2f8LOB3E0MqvKhBMsrxILg

{
    "fecha": "2001/01/21",
    "duracion": 100,
    "actividad": "actividad1",
    "descripcion": "descripcion1",
    "responsable": "responsable1"
}
###
PUT http://localhost:3000/api/records/64bbeecc7f4d6df4a34b4b68
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZnczIyMDAyIiwiaWQiOiI2NGI5MDYwMDljZDMwNjIwMDhkOTAxZjYiLCJpYXQiOjE2OTAwMzc0MTAsImV4cCI6MTY5MDA0MTAxMH0.XK8flz7l04sKBWQ4mwCLk2f8LOB3E0MqvKhBMsrxILg

{
    "fecha": "2013/03/23",
    "duracion": 13,
    "actividad": "a13",
    "descripcion": "d13",
    "responsable": "r13"
}
###
POST http://localhost:3000/api/users
content-type: application/json

{
    "username": "fgs22002",
    "name": "Paco Garcia",
    "password": "fgs"
}
###
GET http://localhost:3000/api/users
###
POST http://localhost:3000/api/login
content-type: application/json

{
    "username": "fgs22002",
    "password": "fgs"
}
